<<<<<<< HEAD
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'yourapp'
    static_configs:
      - targets: ['localhost:8000']
=======
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'yourapp'
    static_configs:
      - targets: ['localhost:8000']
>>>>>>> cbdace2609bddf46d9bc19fb9e3490e8a827ad09
